kind: pipeline
name: default

steps:
  - name: print-node
    image: busybox
    commands:
      - echo "${DRONE_RUNNER_HOSTNAME}"

  - name: test
    image: python:2.7.17
    commands:
      - pip install -r requirements.dev.txt
      - fab setup lint test

  - name: install
    image: python:2.7.17
    commands:
      - pip install -r requirements.dev.txt
      - fab install
