manager: RsyncCopyManager
remotes:
  # osx: ~/Desktop/Saves
  osx: root@192.168.0.10:/var/lib/backups/saves
  # osx: /Volumes/Games/SaveDirs
  windows: \\Trunk\Games\SaveDirs
  cygwin: root@192.168.0.10:/var/lib/backups/saves
variables:
  CYGWIN_USER_DIR: /cygdrive/c/Users/$USER
games:
  - name: Steam
    osx:
      local: ~/Library/Application Support/Steam/userdata
      remote: $REMOTE_ROOT/SteamOSX
  - name: Beat Hazard
    aliases:
      - BeatHazard
    osx:
      local: ~/Library/Application Support/BeatHazard
  - name: Borderlands 2
    aliases:
      - Borderlands2
    cygwin:
      local: $CYGWIN_USER_DIR/Documents/My Games/Borderlands 2/willowgame/
      remote: $REMOTE_ROOT/Borderlands 2
  - name: Car Mechanic Simulator 2015
    aliases:
      - CMS2015
      - CMS
    osx:
      local: ~/Library/Application Support/unity.Red Dot Games.Car Mechanic Simulator 2015
    windows:
      local: C:\Users\Aleem\AppData\LocalLow\Red Dot Games\Car Mechanic Simulator 2015
      remote: $REMOTE_ROOT\CMS2015
  - name: The Crew
    aliases:
      - TheCrew
    cygwin:
      local: $CYGWIN_USER_DIR/Documents/The Crew
  - name: Diablo III
    aliases:
      - D3
    cygwin:
      local: $CYGWIN_USER_DIR/Documents/Diablo III
  - name: Dungeon Siege
    aliases:
      - DungeonSiege
    cygwin:
      local: $CYGWIN_USER_DIR/Documents/Dungeon Siege
  - name: Endless Sky
    aliases:
      - EndlessSky
    osx:
      local: ~/Library/Application Support/endless-sky
  - name: EVE Online
    aliases:
      - EVEOnline
      - EVE
    cygwin:
      local: $CYGWIN_USER_DIR/Documents/EVE
  - name: Factorio
    osx:
      local: ~/Library/Application Support/factorio
  - name: Fallout New Vegas
    aliases:
      - FalloutNewVegas
      - NewVegas
      - FalloutNV
    cygwin:
      local: $CYGWIN_USER_DIR/Documents/My Games/FalloutNV
  - name: Faster Than Light
    aliases:
      - FTL
    osx:
      local: ~/Library/Application Support/FasterThanLight
  - name: Grand Theft Auto V
    aliases:
      - GTAV
      - GTA5
    cygwin:
      local: $CYGWIN_USER_DIR/Documents/Rockstar Games/GTA V
  - name: GRID
    cygwin:
      local: $CYGWIN_USER_DIR/Documents/Codemasters/GRID
  - name: Hero Siege
    aliases:
      - HeroSiege
    osx:
      local: ~/Library/Application Support/com.yoyogames.macyoyorunner
  - name: Just Cause 2
    aliases:
      - JustCause2
      - JC2
    cygwin:
      local: $CYGWIN_USER_DIR/Documents/Square Enix/Just Cause 2
  - name: Prototype
    cygwin:
      local: $CYGWIN_USER_DIR/Documents/Prototype
  - name: Rocket League
    aliases:
      - RocketLeague
    cygwin:
      local: $CYGWIN_USER_DIR/Documents/My Games/Rocket League
  - name: The Sims 4
    aliases:
      - TheSims4
      - Sims4
    cygwin:
      local: $CYGWIN_USER_DIR/Documents/Electronic Arts/The Sims 4
  - name: 'The Elder Scrolls IV: Skyrim'
    aliases:
      - TESIV
      - TES5
      - Skyrim
    cygwin:
      local: $CYGWIN_USER_DIR/Documents/My Games/Skyrim
  - name: Space Pirates and Zombies
    aliases:
      - SPAZ
    osx:
      local: ~/Library/Application Support/spacepiratesandzombies
  - name: Terraria
    osx:
      local: ~/Library/Application Support/Terraria
  - name: Vindictus
    cygwin:
      local: $CYGWIN_USER_DIR/Documents/Vindictus
  - name: The Witcher 3
    aliases:
      - TheWitcher3
      - Witcher3
    cygwin:
      local: $CYGWIN_USER_DIR/Documents/The Witcher 3
